package com.wisea.transac.tp.system.utils.kdniao;

/**
 * 快递公司名称及编码
 * @author wangjiahao
 * @version 1.0
 * @className KdniaoConstants
 * @since 2019-03-11 11:13
 */
public enum KdniaoConstants {

    /**
     * 快递公司名称及编码
     */
    SF("顺丰速运", "SF"),
    HTKY("百世快递", "HTKY"),
    ZTO("中通快递", "ZTO"),
    STO("申通快递", "STO"),
    YTO("圆通速递", "YTO"),
    YD("韵达速递", "YD"),
    YZPY("邮政快递包裹", "YZPY"),
    EMS("EMS", "EMS"),
    HHTT("天天快递", "HHTT"),
    JD("京东快递", "JD"),
    UC("优速快递", "UC"),
    DBL("德邦快递", "DBL"),
    ZJS("宅急送", "ZJS"),
    TNT("TNT快递", "TNT"),

    UPS("UPS", "UPS"),
    DHL("DHL", "DHL"),
    FEDEX("FEDEX联邦(国内件）", "FEDEX"),
    FEDEX_GJ("FEDEX联邦(国际件）", "FEDEX_GJ"),
    AJ("安捷快递", "AJ"),
    ALKJWL("阿里跨境电商物流", "ALKJWL"),
    AX("安迅物流", "AX"),
    AYUS("安邮美国", "AYUS"),
    AMAZON("亚马逊物流", "AMAZON"),
    AOMENYZ("澳门邮政", "AOMENYZ"),
    ANE("安能物流", "ANE"),
    ADD("澳多多", "ADD"),
    AYCA("澳邮专线", "AYCA"),
    AXD("安鲜达", "AXD"),
    ANEKY("安能快运", "ANEKY"),
    BDT("八达通", "BDT"),
    BETWL("百腾物流", "BETWL"),
    BJXKY("北极星快运", "BJXKY"),
    BNTWL("奔腾物流", "BNTWL"),
    BFDF("百福东方", "BFDF"),
    BHGJ("贝海国际", "BHGJ"),
    BFAY("八方安运", "BFAY"),
    BTWL("百世快运", "BTWL"),
    CFWL("春风物流", "CFWL"),
    CHTWL("诚通物流", "CHTWL"),
    CXHY("传喜物流", "CXHY"),
    CG("程光", "CG"),
    CITY100("城市100", "CITY100"),
    CJKD("城际快递", "CJKD"),
    CNPEX("CNPEX中邮快递", "CNPEX"),
    COE("COE东方快递", "COE"),
    CSCY("长沙创一", "CSCY"),
    CDSTKY("成都善途速运", "CDSTKY"),
    CTG("联合运通", "CTG"),
    CRAZY("疯狂快递", "CRAZY"),
    CBO("CBO钏博物流", "CBO"),
    CND("承诺达", "CND"),
    DSWL("D速物流", "DSWL"),
    DLG("到了港", "DLG"),
    DTWL("大田物流", "DTWL"),
    DJKJWL("东骏快捷物流", "DJKJWL"),
    DEKUN("德坤", "DEKUN"),
    DBLKY("德邦快运", "DBLKY"),
    DML("大马鹿", "DML"),
    ETK("E特快", "ETK"),
    EWE("EWE", "EWE"),
    KFW("快服务", "KFW"),
    FKD("飞康达", "FKD"),
    FTD("富腾达", "FTD"),
    FYKD("凡宇货的", "FYKD"),
    FASTGO("速派快递", "FASTGO"),
    FT("丰通快运", "FT"),
    GD("冠达", "GD"),
    GTO("国通快递", "GTO"),
    GDEMS("广东邮政", "GDEMS"),
    GSD("共速达", "GSD"),
    GTONG("广通", "GTONG"),
    GAI("迦递快递", "GAI"),
    GKSD("港快速递", "GKSD"),
    GTSD("高铁速递", "GTSD"),
    HFWL("汇丰物流", "HFWL"),
    HGLL("黑狗冷链", "HGLL"),
    HLWL("恒路物流", "HLWL"),
    HOAU("天地华宇", "HOAU"),
    HOTSCM("鸿桥供应链", "HOTSCM"),
    HPTEX("海派通物流公司", "HPTEX"),
    hq568("华强物流", "hq568"),
    HQSY("环球速运", "HQSY"),
    HXLWL("华夏龙物流", "HXLWL"),
    HXWL("豪翔物流", "HXWL"),
    HFHW("合肥汇文", "HFHW"),
    HLONGWL("辉隆物流", "HLONGWL"),
    HQKD("华企快递", "HQKD"),
    HRWL("韩润物流", "HRWL"),
    HTKD("青岛恒通快递", "HTKD"),
    HYH("货运皇物流", "HYH"),
    HYLSD("好来运快递", "HYLSD"),
    HJWL("皇家物流", "HJWL"),
    JAD("捷安达", "JAD"),
    JGSD("京广速递", "JGSD"),
    JIUYE("九曳供应链", "JIUYE"),
    JXD("急先达", "JXD"),
    JYKD("晋越快递", "JYKD"),
    JYM("加运美", "JYM"),
    JGWL("景光物流", "JGWL"),
    JYWL("佳怡物流", "JYWL"),
    JDKY("京东快运", "JDKY"),
    CNEX("佳吉快运", "CNEX"),
    KYSY("跨越速运", "KYSY"),
    KYWL("跨越物流", "KYWL"),
    KSDWL("快速递物流", "KSDWL"),
    KBSY("快8速运", "KBSY"),
    LB("龙邦快递", "LB"),
    LJSKD("立即送", "LJSKD"),
    LHT("联昊通速递", "LHT"),
    MB("民邦快递", "MB"),
    MHKD("民航快递", "MHKD"),
    MK("美快", "MK"),
    MDM("门对门快递", "MDM"),
    MRDY("迈隆递运", "MRDY"),
    MLWL("明亮物流", "MLWL"),
    NF("南方", "NF"),
    NEDA("能达速递", "NEDA"),
    PADTF("平安达腾飞快递", "PADTF"),
    PANEX("泛捷快递", "PANEX"),
    PJ("品骏快递", "PJ"),
    PCA("PCA Express", "PCA"),
    QCKD("全晨快递", "QCKD"),
    QRT("全日通快递", "QRT"),
    QUICK("快客快递", "QUICK"),
    QXT("全信通", "QXT"),
    RQ("荣庆物流", "RQ"),
    QYZY("七曜中邮", "QYZY"),
    RFD("如风达", "RFD"),
    RRS("日日顺物流", "RRS"),
    RFEX("瑞丰速递", "RFEX"),
    SAD("赛澳递", "SAD"),
    SNWL("苏宁物流", "SNWL"),
    SAWL("圣安物流", "SAWL"),
    SBWL("晟邦物流", "SBWL"),
    SDWL("上大物流", "SDWL"),
    SFWL("盛丰物流", "SFWL"),
    ST("速通物流", "ST"),
    STWL("速腾快递", "STWL"),
    SUBIDA("速必达物流", "SUBIDA"),
    SDEZ("速递e站", "SDEZ"),
    SCZPDS("速呈宅配", "SCZPDS"),
    SURE("速尔快递", "SURE"),
    SS("闪送", "SS"),
    STKD("盛通快递", "STKD"),
    TAIWANYZ("台湾邮政", "TAIWANYZ"),
    TSSTO("唐山申通", "TSSTO"),
    TJS("特急送", "TJS"),
    TYWL("通用物流", "TYWL"),
    UAPEX("全一快递", "UAPEX"),
    ULUCKEX("优联吉运", "ULUCKEX"),
    UEQ("UEQ Express", "UEQ"),
    WJK("万家康", "WJK"),
    WJWL("万家物流", "WJWL"),
    WHTZX("武汉同舟行", "WHTZX"),
    WPE("维普恩", "WPE"),
    WXWL("万象物流", "WXWL"),
    WTP("微特派", "WTP"),
    WTWL("温通物流", "WTWL"),
    XCWL("迅驰物流", "XCWL"),
    XFEX("信丰物流", "XFEX"),
    XYT("希优特", "XYT"),
    XJ("新杰物流", "XJ"),
    YADEX("源安达快递", "YADEX"),
    YCWL("远成物流", "YCWL"),
    YCSY("远成快运", "YCSY"),
    YDH("义达国际物流", "YDH"),
    YDT("易达通", "YDT"),
    YFHEX("原飞航物流", "YFHEX"),
    YFSD("亚风快递", "YFSD"),
    YTKD("运通快递", "YTKD"),
    YXKD("亿翔快递", "YXKD"),
    YUNDX("运东西网", "YUNDX"),
    YMDD("壹米滴答", "YMDD"),
    YZBK("邮政国内标快", "YZBK"),
    YZTSY("一站通速运", "YZTSY"),
    YFSUYUN("驭丰速运", "YFSUYUN"),
    YSDF("余氏东风", "YSDF"),
    YF("耀飞快递", "YF"),
    YDKY("韵达快运", "YDKY"),
    YL("云路", "YL"),
    ZENY("增益快递", "ZENY"),
    ZHQKD("汇强快递", "ZHQKD"),
    ZTE("众通快递", "ZTE"),
    ZTKY("中铁快运", "ZTKY"),
    ZTWL("中铁物流", "ZTWL"),
    SJ("郑州速捷", "SJ"),
    ZTOKY("中通快运", "ZTOKY"),
    ZYKD("中邮快递", "ZYKD"),
    WM("中粮我买网", "WM"),
    ZMKM("芝麻开门", "ZMKM"),
    ZHWL("中骅物流", "ZHWL"),
    //
    AAE("AAE全球专递", "AAE"),
    ACS("ACS雅仕快递", "ACS"),

    ADP("ADP Express Tracking", "ADP"),
    ANGUILAYOU("安圭拉邮政", "ANGUILAYOU"),
    APAC("APAC", "APAC"),
    ARAMEX("Aramex", "ARAMEX"),
    AT("奥地利邮政", "AT"),
    AUSTRALIA("Australia Post Tracking", "AUSTRALIA"),
    BEL("比利时邮政", "BEL"),
    BHT("BHT快递", "BHT"),
    BILUYOUZHE("秘鲁邮政", "BILUYOUZHE"),
    BR("巴西邮政", "BR"),
    BUDANYOUZH("不丹邮政", "BUDANYOUZH"),
    CDEK("CDEK", "CDEK"),
    CA("加拿大邮政", "CA"),
    DBYWL("递必易国际物流", "DBYWL"),
    DDWL("大道物流", "DDWL"),
    DGYKD("德国云快递", "DGYKD"),
    DLGJ("到乐国际", "DLGJ"),
    DHL_DE("DHL德国", "DHL_DE"),
    DHL_EN("DHL(英文版)", "DHL_EN"),
    DHL_GLB("DHL全球", "DHL_GLB"),
    DHLGM("DHL Global Mail", "DHLGM"),
    DK("丹麦邮政", "DK"),
    DPD("DPD", "DPD"),
    DPEX("DPEX", "DPEX"),
    D4PX("递四方速递", "D4PX"),
    EMSGJ("EMS国际", "EMSGJ"),
    EKM("易客满", "EKM"),
    EPS("EPS (联众国际快运)", "EPS"),
    ESHIPPER("EShipper", "ESHIPPER"),
    FCWL("丰程物流", "FCWL"),
    FX("法翔速运", "FX"),
    FQ("FQ", "FQ"),
    FLYZ("芬兰邮政", "FLYZ"),
    FZGJ("方舟国际速递", "FZGJ"),
    GJEYB("国际e邮宝", "GJEYB"),
    GJYZ("国际邮政包裹", "GJYZ"),
    GE2D("GE2D", "GE2D"),
    GT("冠泰", "GT"),
    GLS("GLS", "GLS"),
    IOZYZ("欧洲专线(邮政)", "IOZYZ"),
    IADLYYZ("澳大利亚邮政", "IADLYYZ"),
    IAEBNYYZ("阿尔巴尼亚邮政", "IAEBNYYZ"),
    IAEJLYYZ("阿尔及利亚邮政", "IAEJLYYZ"),
    IAFHYZ("阿富汗邮政", "IAFHYZ"),
    IAGLYZ("安哥拉邮政", "IAGLYZ"),
    IAJYZ("埃及邮政", "IAJYZ"),
    IALBYZ("阿鲁巴邮政", "IALBYZ"),
    IALYYZ("阿联酋邮政", "IALYYZ"),
    IASBJYZ("阿塞拜疆邮政", "IASBJYZ"),
    IBCWNYZ("博茨瓦纳邮政", "IBCWNYZ"),
    IBDLGYZ("波多黎各邮政", "IBDLGYZ"),
    IBDYZ("冰岛邮政", "IBDYZ"),
    IBELSYZ("白俄罗斯邮政", "IBELSYZ"),
    IBHYZ("波黑邮政", "IBHYZ"),
    IBJLYYZ("保加利亚邮政", "IBJLYYZ"),
    IBJSTYZ("巴基斯坦邮政", "IBJSTYZ"),
    IBLNYZ("黎巴嫩邮政", "IBLNYZ"),
    IBOLYZ("波兰邮政", "IBOLYZ"),
    IBTD("宝通达", "IBTD"),
    IBYB("贝邮宝", "IBYB"),
    ICKY("出口易", "ICKY"),
    IDGYZ("德国邮政", "IDGYZ"),
    IWDMLYZ("危地马拉邮政", "IWDMLYZ"),
    IWGDYZ("乌干达邮政", "IWGDYZ"),
    IWKLEMS("乌克兰EMS", "IWKLEMS"),
    IWKLYZ("乌克兰邮政", "IWKLYZ"),
    IWLGYZ("乌拉圭邮政", "IWLGYZ"),
    ILKKD("林克快递", "ILKKD"),
    IWLYZ("文莱邮政", "IWLYZ"),
    IXGLDNYYZ("新喀里多尼亚邮政", "IXGLDNYYZ"),
    IE("爱尔兰邮政", "IE"),
    IXPWL("夏浦物流", "IXPWL"),
    IYDYZ("印度邮政", "IYDYZ"),
    IXPSJ("夏浦世纪", "IXPSJ"),
    IEGDEYZ("厄瓜多尔邮政", "IEGDEYZ"),
    IELSYZ("俄罗斯邮政", "IELSYZ"),
    IFTWL("飞特物流", "IFTWL"),
    IGDLPDYZ("瓜德罗普岛邮政", "IGDLPDYZ"),
    IGSDLJYZ("哥斯达黎加邮政", "IGSDLJYZ"),
    IHGYZ("韩国邮政", "IHGYZ"),
    IHHWL("华翰物流", "IHHWL"),
    IHLY("互联易", "IHLY"),
    IHSKSTYZ("哈萨克斯坦邮政", "IHSKSTYZ"),
    IHSYZ("黑山邮政", "IHSYZ"),
    IJBBWYZ("津巴布韦邮政", "IJBBWYZ"),
    IJEJSSTYZ("吉尔吉斯斯坦邮政", "IJEJSSTYZ"),
    IJKYZ("捷克邮政", "IJKYZ"),
    IJNYZ("加纳邮政", "IJNYZ"),
    IJPZYZ("柬埔寨邮政", "IJPZYZ"),
    IKNDYYZ("克罗地亚邮政", "IKNDYYZ"),
    IKNYYZ("肯尼亚邮政", "IKNYYZ"),
    IKTDWEMS("科特迪瓦EMS", "IKTDWEMS"),
    ILMNYYZ("罗马尼亚邮政", "ILMNYYZ"),
    IMEDWYZ("摩尔多瓦邮政", "IMEDWYZ"),
    IMETYZ("马耳他邮政", "IMETYZ"),
    INRLYYZ("尼日利亚邮政", "INRLYYZ"),
    ISEWYYZ("塞尔维亚邮政", "ISEWYYZ"),
    ISPLSYZ("塞浦路斯邮政", "ISPLSYZ"),
    IWZBKSTYZ("乌兹别克斯坦邮政", "IWZBKSTYZ"),
    IXBYYZ("西班牙邮政", "IXBYYZ"),
    IXJPEMS("新加坡EMS", "IXJPEMS"),
    IXLYZ("希腊邮政", "IXLYZ"),
    IXXLYZ("新西兰邮政", "IXXLYZ"),
    IYDLYZ("意大利邮政", "IYDLYZ"),
    IYGYZ("英国邮政", "IYGYZ"),
    IYMNYYZ("亚美尼亚邮政", "IYMNYYZ"),
    IYMYZ("也门邮政", "IYMYZ"),
    IZLYZ("智利邮政", "IZLYZ"),
    JP("日本邮政", "JP"),
    JFGJ("今枫国际", "JFGJ"),
    JGZY("极光转运", "JGZY"),
    JXYKD("吉祥邮转运", "JXYKD"),
    JLDT("嘉里国际", "JLDT"),
    JPKD("绝配国际速递", "JPKD"),
    SYJHE("佳惠尔", "SYJHE"),
    LYT("联运通", "LYT"),
    LHKDS("联合快递", "LHKDS"),
    SHLDHY("林道国际", "SHLDHY"),
    NL("荷兰邮政", "NL"),
    NSF("新顺丰", "NSF"),
    ONTRAC("ONTRAC", "ONTRAC"),
    OCS("OCS", "OCS"),
    QQYZ("全球邮政", "QQYZ"),
    POSTEIBE("POSTEIBE", "POSTEIBE"),
    PAPA("啪啪供应链", "PAPA"),
    QYHY("秦远海运", "QYHY"),
    VENUCIA("启辰国际", "VENUCIA"),
    RDSE("瑞典邮政", "RDSE"),
    SKYPOST("SKYPOST", "SKYPOST"),
    SWCH("瑞士邮政", "SWCH"),
    SDSY("首达速运", "SDSY"),
    SK("穗空物流", "SK"),
    STONG("首通快运", "STONG"),
    STO_INTL("申通快递国际单", "STO_INTL"),
    JYSD("上海久易国际", "JYSD"),
    TAILAND138("泰国138", "TAILAND138"),
    USPS("USPS美国邮政", "USPS"),
    UPU("万国邮政", "UPU"),
    VCTRANS("中越国际物流", "VCTRANS"),
    XKGJ("星空国际", "XKGJ"),
    XD("迅达国际", "XD"),
    XGYZ("香港邮政", "XGYZ"),
    XLKD("喜来快递", "XLKD"),
    XSRD("鑫世锐达", "XSRD"),
    XYGJ("新元国际", "XYGJ"),
    XYGJSD("ADLER雄鹰国际速递", "XYGJSD"),
    YAMA("日本大和运输(Yamato)", "YAMA"),
    YODEL("YODEL", "YODEL"),
    YHXGJSD("一号线", "YHXGJSD"),
    YUEDANYOUZ("约旦邮政", "YUEDANYOUZ"),
    YMSY("玥玛速运", "YMSY"),
    YYSD("鹰运", "YYSD"),
    YJD("易境达", "YJD"),
    YBG("洋包裹", "YBG"),
    YJ("友家速递", "YJ"),
    //
    AOL("AOL（澳通）", "AOL"),
    BCWELT("BCWELT   ", "BCWELT"),
    BN("笨鸟国际", "BN"),
    UBONEX("优邦国际速运", "UBONEX"),
    UEX("UEX   ", "UEX"),
    YDGJ("韵达国际", "YDGJ"),
    ZY_AG("爱购转运", "ZY_AG"),
    ZY_AOZ("爱欧洲", "ZY_AOZ"),
    ZY_AUSE("澳世速递", "ZY_AUSE"),
    ZY_AXO("AXO", "ZY_AXO"),
    ZY_BH("贝海速递", "ZY_BH"),
    ZY_BDA("八达网", "ZY_BDA"),
    ZY_BEE("蜜蜂速递", "ZY_BEE"),
    ZY_BL("百利快递", "ZY_BL"),
    ZY_BM("斑马物流", "ZY_BM"),
    ZY_BT("百通物流", "ZY_BT"),
    ZY_CM("策马转运", "ZY_CM"),
    ZY_EFS("EFS POST", "ZY_EFS"),
    ZY_ESONG("宜送转运", "ZY_ESONG"),
    ZY_FD("飞碟快递", "ZY_FD"),
    ZY_FG("飞鸽快递", "ZY_FG"),
    ZY_FX("风行快递", "ZY_FX"),
    ZY_FXSD("风行速递", "ZY_FXSD"),
    ZY_FY("飞洋快递", "ZY_FY"),
    ZY_HC("皓晨快递", "ZY_HC"),
    ZY_HYSD("海悦速递", "ZY_HYSD"),
    ZY_JA("君安快递", "ZY_JA"),
    ZY_JD("时代转运", "ZY_JD"),
    ZY_JDKD("骏达快递", "ZY_JDKD"),
    ZY_JDZY("骏达转运", "ZY_JDZY"),
    ZY_JH("久禾快递", "ZY_JH"),
    ZY_JHT("金海淘", "ZY_JHT"),
    ZY_LBZY("联邦转运FedRoad", "ZY_LBZY"),
    ZY_LX("龙象快递", "ZY_LX"),
    ZY_MGZY("美国转运", "ZY_MGZY"),
    ZY_MST("美速通", "ZY_MST"),
    ZY_MXZY("美西转运", "ZY_MXZY"),
    ZY_QQEX("QQ-EX", "ZY_QQEX"),
    ZY_RT("瑞天快递", "ZY_RT"),
    ZY_RTSD("瑞天速递", "ZY_RTSD"),
    ZY_SDKD("速达快递", "ZY_SDKD"),
    ZY_SFZY("四方转运", "ZY_SFZY"),
    ZY_ST("上腾快递", "ZY_ST"),
    ZY_TJ("天际快递", "ZY_TJ"),
    ZY_TM("天马转运", "ZY_TM"),
    ZY_TN("滕牛快递", "ZY_TN"),
    ZY_TPY("太平洋快递", "ZY_TPY"),
    ZY_TSZ("唐三藏转运", "ZY_TSZ"),
    ZY_TWC("TWC转运世界", "ZY_TWC"),
    ZY_RDGJ("润东国际快线", "ZY_RDGJ"),
    ZY_TX("同心快递", "ZY_TX"),
    ZY_TY("天翼快递", "ZY_TY"),
    ZY_DGHT("德国海淘之家", "ZY_DGHT"),
    ZY_DYW("德运网", "ZY_DYW"),
    ZY_WDCS("文达国际DCS", "ZY_WDCS"),
    ZY_TZH("同舟快递", "ZY_TZH"),
    ZY_UCS("UCS合众快递", "ZY_UCS"),
    ZY_XC("星辰快递", "ZY_XC"),
    ZY_XF("先锋快递", "ZY_XF"),
    ZY_XIYJ("西邮寄", "ZY_XIYJ"),
    ZY_YQ("云骑快递", "ZY_YQ"),
    ZY_YSSD("优晟速递", "ZY_YSSD"),
    ZY_YTUSA("运淘美国", "ZY_YTUSA"),
    ZY_ZCSD("至诚速递", "ZY_ZCSD"),
    ZYZOOM("增速海淘", "ZYZOOM"),
    ZH("中驰物流", "ZH"),
    ZO("中欧快运", "ZO"),
    ZSKY("准实快运", "ZSKY"),
    ZWSY("中外速运", "ZWSY"),
    ZZJH("郑州建华", "ZZJH");

    private String name;
    private String code;

    KdniaoConstants(String name, String code) {
        this.name = name;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }}
