spring:
  profiles:
    include: cmn
  datasource: #spring boot数据源配置
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid连接池作为数据源
    url: jdbc:mysql://mysql-pxc.percona-xtradb-cluster.svc:3306/wiicsp-cultivar?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: wiicsp-cultivar
    password: NHezEf1g
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 5 # Redis数据库索引(默认为0)
    timeout: 20000 # 连接超时时间（毫秒）
    sentinel:
      master: mymaster
      nodes:
        - rfs-redisfailover.default.svc:26379
  redisson:
    enable: true
    mode: sentinel
    sentinel:
      master: mymaster
      failMax: 180000
      nodes: rfs-redisfailover.default.svc:26379

wbfc:
  mssurl:
    equipment: http://cultivar-equipment
    security: http://cultivar-operation
    system: http://cultivar-operation
    files: http://cultivar-operation
#InfluxDB（时序数据库）配置
influx:
  enable: true
  openurl: http://influxdb-svc.influxdb.svc:8086
  username:
  password:
  database: cultivar
  retentionPolicy: cultivar_policy
  dataDuration: INF #数据永久有效

#物联网设备配置
equipment:
  xaircraft: #极飞物联配置 V5
    enable: true
    account: yuntea #用户名
    password: leon123123 #密码（明文）
    clientID: s35SQbEAyxk #客户端唯一标示
    secret: 49eb15d52436d9c2 #密钥
    baseUrl: https://api.iot.xa.com
    loginUrl: /v5/login
    deviceInfoUrl: /v5/clients/{0}/devices/{1} #/v5/clients/:account/devices/:device_id
    lastPointUrl: /v5/clients/{0}/devices/{1}/datapoints/last #/v5/clients/:account/devices/:device_id/datapoints/last
  jxiotcity:
    enable: true
    port: 8888
    pingInterval: 5

logging: # 日志输出配置
  level:
    com.wisea: DEBUG
