server:
  port: 8950
spring:
  application:
    name: cultivar-plant

wbfc:
  swaggerui:
    enable: true
    title: 新盟风控果品产业互联网综合服务平台-种植综合服务-种植
  quartz:
    auto-resume:
      enabled: true
    timer:
      job: cultivar.palnt.timer.job # 任务分组
      trigger: cultivar.palnt.timer.trigger # 触发器分组
    factory:
      properties:
        "[org.quartz.scheduler.instanceName]": cultivar_palnt_scheduler
  sms:
    test: true # 短信测试 如果是测试 验证码都是999999 默认false false:非测试 true:测试
    productName: 华信 # 第三方短信平台名称
    dictType: sms_template_type # 短信模板数据字典类型 默认:sms_template_type
    smsCodeLabel: smsCode # 手机验证码模板数据字典label 默认:smsCode
    code:
      type: 0 # 手机验证码类型类型(0:数字 1:英文 2：英数混合) 默认:0
      length: 6 # 手机验证码长度 默认:6位
      timeout: 600 # 手机验证码过期时间(默认:600秒)
      reSend: 6 # 手机验证码重发间隔(默认:60秒)
      maxCount: 20 # 同一手机号最大次数
      maxRepeat: 86400 # 同一手机号最大次数校验间隔(默认:24*60*60秒=86400秒)(24小时)
    recive:
      timeout: 86400 # 短信接收过期时间(服务器收到短信缓存到redis的时间)(默认:24*60*60秒=86400秒)(24小时)
    overage:
      warning: true # 短信余额报警 false:不报警 true:报警
      warningMin: 100 # 短信余额最小值边界 默认:100
      emailUser: admin # 报警发送邮件用户(登录名，发送到邮箱,默认admin)
      #email: xudl@wisea.com.cn # 报警发送邮件地址(此项与emailUser互斥)
      emailTemplete: /emailFile/emailOverage.ftl # 短信余额报警邮件 默认：/src/main/resources/templates/emailFile/emailOverage.ftl /src/main/resources/templates为ftl模板文件默认目录
    huaxin:
      username: OM00023 # 华信用户名
      password: 3ud3ch # 华信密码
      sendUrl: https://dx.ipyy.net/smsJson.aspx # 华信发送URL
      overageUrl: https://dx.ipyy.net/smsJson.aspx # 华信获取余额URL

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

feign:
  httpclient:
    connection-timeout: 30000
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 30000
        readTimeout: 30000
