spring:
  redis: 
    host: 192.168.20.233 # Redis服务器地址
    database: 39 # Redis数据库索引(默认为0)
    timeout: 20000 # 连接超时时间（毫秒）

wbfc:
  mssurl:
    seller: http://TRANSAC-SELLER
  conf:
    enable: true
    url1: http://192.168.20.208/ori

logging:
  level:
    com.wisea: debug

management:
  endpoint:
    env:
      post:
        enabled: true # 开启环境变量可修改
    logviewer:
      enabled: true # 开启实时日志节点
    restart:
      enabled: true # 开启热重启