product:
  elasticIpAddress: 192.168.20.33
  elasticPort: 39200
  index-name: transac-dktest
  user: elastic
  password: xdj69bkrxgw8jmhjl4ghqnhr

logging: # 日志输出配置
  level:
    com.wisea.transac.common.dao: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.20.5:2105/eureka/ # 指向配置eureka地址

wbfc:
  swaggerui:
    enable: true
    title: 新盟风控果品产业互联网综合服务平台-交易服务-商品平台
  mssurl:
    tp-system: http://transac-tp-system
    seller: http://transac-seller
    security: http://transac-operation
    system: http://transac-operation
    files: http://transac-operation
