server:
  port: 8941
spring:
  application:
    name: transac-operation # 新盟风控果品产业互联网综合服务平台-交易服务-运营平台

wbfc:
  quartz:
    timer:
      job: wiicsp.operation.timer.job # 任务分组
      trigger: wiicsp.operation.timer.trigger # 触发器分组
    factory:
      properties:
        "[org.quartz.scheduler.instanceName]": wiicsp_operation_scheduler

management:
  #  endpoint:
  #    database:
  #      enabled: true # 开启数据库监控节点
  #    logviewer:
  #      enabled: true # 开启实时日志节点
  health:
    elasticsearch:
      enabled: false # 排除elastic健康监控 虽然backup工程引用了es的包，但配置是在页面进行的 这里启动不需要连接
